# Generated by Django 3.2.10 on 2023-04-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablets', '0003_auto_20180207_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='level',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='lft',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='rght',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='template',
            name='template_engine',
            field=models.IntegerField(choices=[(1, 'Django')], default=1, verbose_name='Template Engine'),
        ),
    ]
